import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from './Components/Header'
import PlanTripCard from './Components/PlanTripCard/PlanTrip'
import background from '../assets/background.png'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>A6 Aviation</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    <div className={styles.header_main_container}
     style={{
      backgroundImage: `url(${background.src})`,
      width: '100%',
      height: '850px',
      backgroundRepeat:'no-repeat'
    }}>
      <Header/>
      <div className={styles.main_text_container}>
        <p className={styles.small_orange_text}>A6 AVIATION GlOBAL CHARTER SERVICES</p>
        <p className={styles.big_text}>The joy is coming back</p>
        <p className={styles.small_white_text}>It's Arrived,The Premium Economy You've Been Waiting For</p>
      </div>
      
    </div>
    <PlanTripCard/>
      
    </div>
  )
}

export default Home
